# Ref: https://docs.codecov.com/docs/codecovyml-reference#
comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

coverage:
  status:
    project:
      default:
        flags: 
          - frontend
        target: auto
        # target: 80%   # the required coverage value
        threshold: 10%  # the leniency in hitting the target