name: Danger CI

on:
  pull_request:
    branches:
      - 'staging'

jobs:
  test:
    name: Danger CI

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Get yarn cache directory path
      id: cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: cache # use this to check for `cache-hit` (`steps.cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.cache-dir-path.outputs.dir }}          
        key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'    
      run: yarn install
    
    - name: Danger CI Check
      uses: danger/danger-js@9.1.8
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.Gh_TOKEN }}
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}