# Ref: https://github.com/wangchucheng/git-repo-sync
name: Gitlab RepoSync

on:
  push:
    branches:
      - production
      - staging
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Gitlab Repo Sync
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Mirror to Gitlab
      uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        # Such as https://gitlab.com/BrianLusina/some-repo-sync.git
        target-url: ${{ secrets.GITLAB_REPO_URL }}
        # Such as BrianLusina
        target-username: ${{ secrets.GITLAB_USERNAME }}
        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
        target-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}